version: '3'
services:
  webapp:
    #  the build command tells compose it's building this image
    build:
        # Will build in the current directory
        context: .
        #  by passing a name here you are telling compose to name and tag the built image by this name
    image: FLASKAPP
    environment:
      - FLASK_ENV=development
    ports:
        - '4000:5000'
  redis:
    image: redis:4.0.11-alpine
